### ISSUE TITLE
Compatibility with Zend Framework 3

### ISSUE THREAD

**Issue by mrploddy1981** [zendframework/ZendService_ReCaptcha#9]
Hi there,

Are there any plans to update this module for compatibility with Zend Framework 3 at all ? The Zend_Captcha module references this and when you try to pull it down via composer it fails due to version requirements. 

Thanks

**Comment by joepsyko** [comment]
Hi,

I created a pull request to fix this a few days ago.

Joe

**Comment by akrabat** [comment]
Fixed with #11
